apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"   # needed for Jupyter
  name: cinder
parameters:
  availability: nova
provisioner: kubernetes.io/cinder

